insert into public.projects (
  slug,
  title,
  category,
  timeline,
  summary,
  impact,
  problem,
  solution,
  role,
  stack,
  highlights,
  responsibilities,
  results,
  main_image_url,
  gallery,
  featured,
  sort_order,
  is_public
) values
(
  'doctolik-desktop-companion',
  'Secure Desktop Companion for Doctolik',
  'Healthcare Desktop App',
  'Sep 2025 - Present',
  'A cross-platform Electron application synchronized with server-side medical operations for offline-first workflows.',
  'Supports medical teams with encrypted local data, authenticated sync, and secure update delivery.',
  'Healthcare workflows cannot pause when internet connectivity is weak, but sensitive local patient and operational data must stay protected.',
  'A secure Electron architecture with SQLCipher encrypted local storage, authenticated server synchronization, and controlled auto-update delivery.',
  'Owned the desktop architecture, encrypted storage strategy, authentication flow, synchronization logic, and release pipeline direction.',
  ARRAY['Electron','React','SQLCipher','Laravel','JWT','CI/CD'],
  ARRAY['Implemented SQLCipher encrypted storage and authenticated synchronization.','Designed secure release and in-app auto-update workflows.','Improved reliability for medical workflow continuity when connectivity is limited.'],
  ARRAY['Designed the offline-first data flow and local persistence model.','Connected the desktop client with Laravel-backed server operations.','Planned secure release behavior for production users.'],
  ARRAY['Enabled medical users to continue work when connectivity is limited.','Improved security posture through encrypted local storage.','Created a stronger foundation for maintainable desktop releases.'],
  '/karim-engineering-hero.png',
  '[{"src":"/karim-engineering-hero.png","alt":"Secure healthcare desktop workflow dashboard","caption":"Secure desktop environment with medical workflow, sync, and protection cues."},{"src":"/mobile-laravel-project.png","alt":"Connected mobile and API workflow","caption":"API-backed product surfaces connected to backend operations."}]'::jsonb,
  true,
  10,
  true
),
(
  'doctolik-medical-platform',
  'Doctolik Medical Platform',
  'Laravel Health-Tech Platform',
  '2025 - Present',
  'Production healthcare platform with payment, prescription, maintenance, and operational modules.',
  'Improved stability, security posture, and product delivery for 40+ healthcare professionals.',
  'The medical platform needed continuous product delivery while handling sensitive workflows, critical bugs, payment logic, prescriptions, and long-term architecture decisions.',
  'A production Laravel workflow with React, Livewire, Alpine.js, Filament, CI/CD, and maintenance practices that balance speed with reliability.',
  'Led full-stack delivery, maintenance, roadmap planning, bug/security fixes, and module development.',
  ARRAY['Laravel','React','Livewire','Alpine.js','Filament','Docker'],
  ARRAY['Led frontend and backend delivery across critical medical workflows.','Shipped security fixes, bug repairs, and roadmap-driven architecture improvements.','Supported CI/CD and deployment automation for reliable releases.'],
  ARRAY['Built and maintained Laravel modules for medical operations.','Improved architecture, reliability, and security posture.','Coordinated practical technical priorities for a startup team.'],
  ARRAY['Supported 40+ healthcare professionals through production workflows.','Shipped payment and prescription features plus critical patches.','Reduced product risk through better deployment and maintenance habits.'],
  '/karim-engineering-hero.png',
  '[{"src":"/karim-engineering-hero.png","alt":"Medical product platform workspace","caption":"Health-tech platform concept with workflow and security-oriented product surfaces."},{"src":"/mobile-laravel-project.png","alt":"Mobile and backend product workflow","caption":"Product interfaces supported by Laravel APIs and deployment workflows."}]'::jsonb,
  true,
  20,
  true
),
(
  'mobile-product-apps',
  'Mobile Product Apps',
  'React Native / Expo',
  'Ongoing',
  'Mobile app work focused on practical product flows, fast iteration, and API-backed experiences.',
  'Bridges Laravel backend expertise with mobile interfaces for founders and product teams.',
  'Many startup products need mobile experiences that are connected to robust backend APIs without creating duplicated business logic or fragile release flows.',
  'React Native and Expo app delivery backed by Laravel APIs, reusable UI patterns, and product-oriented integration decisions.',
  'Designed mobile flows, connected screens to backend services, and translated backend product logic into usable app experiences.',
  ARRAY['React Native','Expo','TypeScript','Laravel APIs','REST'],
  ARRAY['Built and integrated mobile-first flows with API-backed data.','Applied reusable UI patterns across web and mobile surfaces.','Focused on maintainability, responsive interactions, and product clarity.'],
  ARRAY['Structured mobile screens around real user tasks.','Integrated API-backed data flows and authentication-aware experiences.','Kept the UI maintainable for future startup iteration.'],
  ARRAY['Created a stronger bridge between Laravel backend systems and mobile users.','Improved product readiness for mobile-first workflows.','Showed practical cross-platform delivery beyond web-only engineering.'],
  '/mobile-laravel-project.png',
  '[{"src":"/mobile-laravel-project.png","alt":"React Native app connected to Laravel backend","caption":"Mobile product surfaces connected to backend API and deployment signals."},{"src":"/karim-engineering-hero.png","alt":"Full-stack engineering workstation","caption":"Full-stack workspace tying mobile, backend, and secure systems together."}]'::jsonb,
  true,
  30,
  true
)
on conflict (slug) do update set
  title = excluded.title,
  category = excluded.category,
  timeline = excluded.timeline,
  summary = excluded.summary,
  impact = excluded.impact,
  problem = excluded.problem,
  solution = excluded.solution,
  role = excluded.role,
  stack = excluded.stack,
  highlights = excluded.highlights,
  responsibilities = excluded.responsibilities,
  results = excluded.results,
  main_image_url = excluded.main_image_url,
  gallery = excluded.gallery,
  featured = excluded.featured,
  sort_order = excluded.sort_order,
  is_public = excluded.is_public;

insert into public.learning_resources (
  title,
  resource_type,
  status,
  focus,
  notes,
  sort_order,
  is_public
) values
('Production Laravel Architecture','track','Active focus','Advanced backend structure, API design, payment flows, security, and maintainable SaaS modules.','Used as the core portfolio positioning for full-stack and Laravel-heavy roles.',10,true),
('React Native and Expo Product Apps','track','Active focus','Mobile app UI, API integration, reusable product flows, and cross-platform delivery.','Emphasizes the mobile-app side of Karim''s skill set for startup and product teams.',20,true),
('MLOps with PyTorch and Optuna','course','In progress','Training reproducibility, hyperparameter tuning, model lifecycle, and automated experiments.','Supports AI Engineer, ML Engineer, and MLOps Engineer role targeting.',30,true),
('Secure Desktop Delivery with Electron','video','Documenting','SQLCipher, offline-first storage, authenticated sync, signed releases, and auto-update workflows.','A strong candidate for a future technical walkthrough video or case study.',40,true)
on conflict do nothing;

insert into public.contributions (
  title,
  contribution_kind,
  organization,
  timeline,
  summary,
  stack,
  contribution,
  outcome,
  link,
  sort_order,
  is_public
) values
(
  'Doctolik product and platform contribution',
  'startup',
  'Doctolik',
  'Sep 2025 - Present',
  'Contributed as a core developer and maintainer across a healthcare product where production reliability, user trust, and secure delivery matter.',
  ARRAY['Laravel','React','Electron','SQLCipher','Docker','GitLab CI/CD'],
  ARRAY['Maintained production modules and resolved critical bugs/security issues.','Improved technical roadmap, release hygiene, and system architecture.','Built desktop companion capabilities connected to server-side medical workflows.'],
  'Helped stabilize and extend a medical product used by healthcare professionals.',
  null,
  10,
  true
),
(
  'laravel-rater package',
  'open-source',
  'Laravel ecosystem',
  'Open source',
  'Published reusable package work for multi-rater, multi-target rating behavior in Laravel applications.',
  ARRAY['Laravel','PHP','Package development'],
  ARRAY['Designed reusable rating abstractions.','Structured package logic for use across multiple application models.','Shared implementation publicly for Laravel developers.'],
  'Adds a public contribution signal and package-design proof to Karim''s Laravel profile.',
  'https://github.com/karimaouaouda',
  20,
  true
),
(
  'University peer mentoring and architecture support',
  'mentoring',
  'Academic community',
  'Ongoing',
  'Supported peers with system design, project architecture, debugging, and practical implementation choices.',
  ARRAY['Laravel','React','Python','Git','System design'],
  ARRAY['Explained architecture and implementation tradeoffs to peers.','Helped structure academic and personal software projects.','Shared practical debugging and delivery habits.'],
  'Shows communication, leadership, and team-growth potential beyond solo implementation.',
  null,
  30,
  true
)
on conflict do nothing;
